# Generated by Django 4.2.27 on 2026-02-10 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='prix')),
                ('prix_negociable', models.BooleanField(default=True, verbose_name='prix négociable')),
                ('ville', models.CharField(max_length=100, verbose_name='ville')),
                ('code_postal', models.CharField(max_length=10, verbose_name='code postal')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('active', 'Active'), ('vendu', 'Vendu'), ('expiree', 'Expirée'), ('rejetee', 'Rejetée'), ('archivee', 'Archivée')], default='en_attente', max_length=20, verbose_name='statut')),
                ('type_annonce', models.CharField(choices=[('offre', 'Offre'), ('demande', 'Demande'), ('echange', 'Échange'), ('location', 'Location'), ('don', 'Don')], default='offre', max_length=20, verbose_name='type')),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('tres_bon', 'Très bon'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('a_renover', 'À rénover')], default='bon', max_length=20, verbose_name='état')),
                ('vues', models.PositiveIntegerField(default=0)),
                ('favoris_count', models.PositiveIntegerField(default=0)),
                ('est_promue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('icone', models.CharField(default='mdi-tag', max_length=50, verbose_name='icône')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('couleur', models.CharField(default='#06D6A0', max_length=7, verbose_name='couleur')),
                ('ordre', models.IntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('symbole', models.CharField(max_length=5, verbose_name='symbole')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('taux_vers_eur', models.FloatField(default=1.0, verbose_name='taux vers EUR')),
                ('actif', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnnonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='annonces/')),
                ('est_principale', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_signalement', models.CharField(choices=[('inapproprie', 'Contenu inapproprié'), ('arnaque', 'Arnaque'), ('faux', 'Information fausse'), ('duplicata', 'Duplicata'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='api.annonce')),
            ],
        ),
    ]
